spring.application.name=ProyectoTrivial

# Render asigna el puerto en una variable de entorno llamada PORT
# puerto dinámico
server.port=${PORT:8080}  
# permitir conexiones externas
server.address=0.0.0.0

# Pool reducido
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# --- MySQL Clever Cloud ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

