# spring.datasource.url=jdbc:h2:mem:proyectotrivial;DB_CLOSE_DELAY=-1;MODE=MariaDB
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


spring.application.name=ProyectoTrivial

server.port=8080

# --- H2 en memoria ---
spring.datasource.url=jdbc:h2:mem:proyectotrivial;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
